In [12]:
import numpy as np 


In [19]:
train_pack = [[[0, 0, 0], 0],
              [[0, 0, 1], 0],
              [[0, 1, 0], 0],
              [[1, 0, 0], 0]]
# train_pack = np.column_stack(train_pack)


In [20]:
def data_prepare(data):
    X = list()
    Y = list()
    for item in data:
        X.append(item[0])
        Y.append(item[1])

        
    X = np.array(X)
    Y = np.array(Y)
    return (X, Y)


In [21]:
train_x, train_y = data_prepare(train_pack)

In [32]:
print(train_x.shape, train_x,'\n\n', train_y)

(4, 3) [[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]] 

 [0 0 0 0]


In [46]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [49]:
w_1 = np.random.normal(0.0, 1, (2, 3))
w_2 = np.random.normal(0.0, 1, (3, 1))
w_3 = np.random.normal(0.0, 1, (1, 2))

In [58]:
output_1 = np.dot(w_1, w_2)
print(output_1)
output_2 = sigmoid(output_1)
print('\n', output_2)
print('\n', output_1.T)
print('\n', output_1)

[[-0.37750133]
 [-1.36293321]]

 [[0.40672969]
 [0.20376399]]

 [[-0.37750133 -1.36293321]]

 [[-0.37750133]
 [-1.36293321]]


In [56]:
output_2 = sigmoid(np.dot(output_1.T, output_2))

In [57]:
print(output_2)

[[0.39382604]]


In [71]:
input_m = [[0, 0, 0],
           [1, 1, 1],
           [0, 0, 0],
           [0, 0, 0]]

def fromDownToUp(m):
    side_m = [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]]
    
    d_size = len(m) - len(side_m)
    for i, row in enumerate(m):
        if i >= d_size:
            side_m[i-d_size] = row
            
    print('before upping\n')
    print(np.array(side_m))
    print('\n')
    
    for i, row in enumerate(m):
        if i < len(side_m):
            side_m[i] = row
    
    print('after upping\n')
    print(np.array(side_m))
    print('\n')

In [72]:
fromDownToUp(input_m)

before upping

[[1 1 1]
 [0 0 0]
 [0 0 0]]


after upping

[[0 0 0]
 [1 1 1]
 [0 0 0]]




In [1]:
def stab(x):
    if x >= 0.65:
        y = 1
    else:
        y = 0
    return y



In [13]:
A = [0.77, 0.13, 0.41]

In [14]:
A = np.array(A)

A = stab(A)
print(A)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [6]:
print(B)

In [8]:
for b in B:
    print(b)

0
0


In [9]:
len(B)

TypeError: object of type 'map' has no len()

In [15]:
e = ['a', 'd', 'r']


In [23]:
w = [[0.23, 0.50, 0.31],
     [0.23, 0.50, 0.31]]
w = np.array(w)
s = np.argmax(w)
print(s)

1


In [24]:
e[s]

'd'

In [25]:
w.shape


(2, 3)

In [26]:
a, b = w.shape


In [2]:
from .mathmethods import Matrix

ImportError: attempted relative import with no known parent package

In [3]:
import numpy as np


In [4]:
p = np.array([1, 2, 3])

In [ ]:
p[]